name = "LuckyImaging"
uuid = "a481cd35-27bf-4482-9964-852a9d15a5e7"
authors = ["Miles Lucas <mdlucas@hawaii.edu> and contributors"]
version = "0.1.0"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
julia = "1.5"
AbstractFFTs = "1"
FFTW = "1.4"